# Generated by Django 5.2.6 on 2025-09-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student')], default=2),
        ),
    ]
