# Generated by Django 5.2.6 on 2025-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
