# Generated by Django 5.2.6 on 2025-09-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_qr_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimstudent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='dimstudent',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimstudent',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimstudent',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
