# Generated by Django 5.2.6 on 2025-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dimstudent_gender_dimstudent_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimstudent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='other', max_length=10),
        ),
    ]
