# Generated by Django 5.2.6 on 2025-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dimstudent_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimstudent',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
