# Generated by Django 5.2.6 on 2025-09-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dimstudent_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimstudent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dimstudent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dimstudent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dimstudent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dimstudent',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='other', max_length=10),
        ),
    ]
